### ISSUE TITLE
Some TEX containers do not pack properly

### ISSUE THREAD

**Issue by jackic2** [derplayer/DCBerserkTextureTool#1]
I have been using the tool for the past few days and I found out that some of the TEX containers can indeed be decompressed but they are unusable once recompressed, as an example M_WORLD.TEX will crash the tool when trying to decompress it AFTER having compressed it with the same tool, even with no changes made.

EDIT: It seems to happen if the filename has an underscore (_) in it, renaming the file before unpacking seems to work fine.

**Comment by jackic2** [comment]
Fixed my issue renaming the files before and after using the tool.

**Comment by derplayer** [comment]
Fixed it in newest version. It would not crash on my pc but the packed M_WORLD.TEX and other files with underscore would be corrupt.
